title: XIII SHCU
author: © Associação Nacional de Pesquisa e Pós-graduação em Planejamento Urbano e Regional (Anpur)
email: secretaria@anpur.org.br
description: >
  PEIXOTO, E. R.; PALAZZO, P. P.; DERNTL, M. F.; TREVISAN, R. (orgs.)
  Tempos e Escalas da Cidade e do Urbanismo:
  XIII Seminário de História da Cidade e do Urbanismo. Anais.
  Brasília: Faculdade de Arquitetura e Urbanismo da Universidade de Brasília, 2014.
  ISBN 978-85-60762-19-4
baseurl: ""
url: "https://shcu2014.com.br"
lang: pt

show_excerpts: false # set to true to show excerpts on the homepage

collections:
  cotidiano:
    output: true
  discurso:
    output: true
  representacoes:
    output: true
  territorio:
    output: true
  poster:
    output: true

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%e %B %Y"

  # generate social links in footer
  social_links:
    #twitter: jekyllrb
    github:  dmcpatrimonio
    # devto: jekyll
    # dribbble: jekyll
    facebook: LabeUrbe
    # flickr:   jekyll
    instagram: anpur2019
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

readme_index:
  enabled:          true
  remove_originals: true
  with_frontmatter: true

header_pages:
 - anais.md
 - organizacao.md

# Build settings
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - kramdown
    # The following plugins are always used by GH-Pages
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links
