title: Tempos e Escalas da Cidade e do Urbanismo
author:
  - name: Elane Ribeiro Peixoto
  - name: Pedro P. Palazzo
  - name: Maria Fernanda Derntl
  - name: Ricardo Trevisan
email: secretaria@anpur.org.br
description: >
  XIII Seminário de História da Cidade e do Urbanismo
baseurl: ""
url: "https://shcu2014.com.br"
lang: pt-BR

permalink: /:categories/:title:output_ext

show_excerpts: false # set to true to show excerpts on the homepage

collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"

kramdown:
  header_offset: 1
  parse_block_html: true
  parse_span_html: true

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%e %B %Y"
  sass_dir: _sass

  # generate social links in footer
  social_links:
    #twitter: jekyllrb
    github:  dmcpatrimonio
    # devto: jekyll
    # dribbble: jekyll
    facebook: LabeUrbe
    # flickr:   jekyll
    instagram: anpur2019
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

readme_index:
  enabled:          true
  remove_originals: true
  with_frontmatter: true

header_pages:
  - eixos-tematicos.md
  - anais.md
  - organizacao.md

# Build settings
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - kramdown
    # The following plugins are always used by GH-Pages
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links
