name: Website build

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test build website
        run: >
          docker run -v "`${{ github_workspace }}`:/srv/jekyll"
        jekyll/jekyll:pages /bin/bash -c
        "chmod 777 /srv/jekyll && jekyll build --future"
